name: gamespedia
description: A new Flutter project.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=2.7.0 <3.0.0'

cupertino_icons: ^1.0.2

dependencies:
  design_system:
    path: packages/design_system
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  fonts:
    - family: SilkScreen
      fonts:
        - asset: assets/fonts/slkscr.ttf
        - asset: assets/fonts/slkscrb.ttf
    - family: DisposableDroid
      fonts:
        - asset: assets/fonts/DisposableDroidBB.ttf
        - asset: assets/fonts/DisposableDroidBB_bld.ttf
  assets:
    - assets/images/
    - assets/images/icons/
    - assets/json/
